apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hivqvv8au-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hivqvv8au-go 
  name: hivqvv8au-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hivqvv8au-go 
