apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hivqvv8au-go 
  janus-idp.io/tekton: hivqvv8au-go
  backstage.io/kubernetes-id: hivqvv8au-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hivqvv8au-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  