apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: hivqvv8au-go-gitops
  description: This is GitOps manifest for hivqvv8au-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: hivqvv8au-go
    backstage.io/kubernetes-id: hivqvv8au-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: hivqvv8au-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:hivqvv8au-go
